package postgres

import "testing"

// TestMintScriptsByteIdenticalToV600 pins the rendered mint scripts to the EXACT
// bytes inforge v6.0.0 produced (goldens generated by running v6.0.0's actual code,
// not transcribed by hand).
//
// Why byte identity is load-bearing: the rendered mint script is the `-mint`
// remote.Command's Triggers input. Any byte change forces a Pulumi REPLACE, and the
// command is DeleteBeforeReplace — so Pulumi first runs the delete script RECORDED IN
// STATE by the previous deploy. Every stack deployed before v6.1.1 recorded the
// broken pre-#225 drop script (no per-database REASSIGN/DROP OWNED clears), whose
// `DROP ROLE` fails with "cannot be dropped because some objects depend on it" and
// aborts the deploy mid-flight. That is exactly how v6.1.0 took production down.
//
// v6.1.1's job is to refresh the recorded delete via a pure `[diff: ~delete]` UPDATE
// — which Pulumi only performs when the create/update/triggers inputs are unchanged.
// Hence: these scripts must not change by a single byte until Triggers are retired
// from the mint commands (the follow-up release), after which a mint-script change
// is an in-place update and this test can be deleted along with the constraint.
//
// If this test fails, DO NOT update the goldens — you are about to re-arm the
// landmine. Move your mint-script change to the post-Triggers-retirement release.
func TestMintScriptsByteIdenticalToV600(t *testing.T) {
	t.Parallel()

	rw, err := MintRoleScript(5432, "ROLE", "PASSWORD", "DATABASE", "rw")
	if err != nil {
		t.Fatalf("MintRoleScript rw: %v", err)
	}
	if rw != goldenMintRW {
		t.Errorf("MintRoleScript rw diverged from v6.0.0 bytes\n--- got ---\n%s\n--- want (v6.0.0) ---\n%s", rw, goldenMintRW)
	}

	ro, err := MintRoleScript(5432, "ROLE", "PASSWORD", "DATABASE", "ro")
	if err != nil {
		t.Fatalf("MintRoleScript ro: %v", err)
	}
	if ro != goldenMintRO {
		t.Errorf("MintRoleScript ro diverged from v6.0.0 bytes\n--- got ---\n%s\n--- want (v6.0.0) ---\n%s", ro, goldenMintRO)
	}

	mon := MintMonitorRoleScript(5432, "ROLE", "PASSWORD", []string{"DB1", "DB2"})
	if mon != goldenMintMonitor {
		t.Errorf("MintMonitorRoleScript diverged from v6.0.0 bytes\n--- got ---\n%s\n--- want (v6.0.0) ---\n%s", mon, goldenMintMonitor)
	}
}

const goldenMintRW = `sudo -u postgres psql -p 5432 -w -v ON_ERROR_STOP=1 -d 'DATABASE' <<'INFORGE_PGSQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ROLE') THEN
    CREATE ROLE "ROLE" LOGIN PASSWORD 'PASSWORD';
  ELSE
    ALTER ROLE "ROLE" WITH LOGIN PASSWORD 'PASSWORD';
  END IF;
END
$$;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON DATABASE "DATABASE" FROM "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM "ROLE";
GRANT CONNECT ON DATABASE "DATABASE" TO "ROLE";
GRANT USAGE, CREATE ON SCHEMA public TO "ROLE";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "ROLE";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "ROLE";
INFORGE_PGSQL`

const goldenMintRO = `sudo -u postgres psql -p 5432 -w -v ON_ERROR_STOP=1 -d 'DATABASE' <<'INFORGE_PGSQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ROLE') THEN
    CREATE ROLE "ROLE" LOGIN PASSWORD 'PASSWORD';
  ELSE
    ALTER ROLE "ROLE" WITH LOGIN PASSWORD 'PASSWORD';
  END IF;
END
$$;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "ROLE";
REVOKE ALL PRIVILEGES ON DATABASE "DATABASE" FROM "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM "ROLE";
GRANT CONNECT ON DATABASE "DATABASE" TO "ROLE";
GRANT USAGE ON SCHEMA public TO "ROLE";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "ROLE";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO "ROLE";
INFORGE_PGSQL`

const goldenMintMonitor = `sudo -u postgres psql -p 5432 -w -v ON_ERROR_STOP=1 <<'INFORGE_PGSQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ROLE') THEN
    CREATE ROLE "ROLE" LOGIN PASSWORD 'PASSWORD';
  ELSE
    ALTER ROLE "ROLE" WITH LOGIN PASSWORD 'PASSWORD';
  END IF;
END
$$;
GRANT pg_monitor TO "ROLE";
GRANT CONNECT ON DATABASE "DB1" TO "ROLE";
GRANT CONNECT ON DATABASE "DB2" TO "ROLE";
INFORGE_PGSQL`
