name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-test:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-go@v6.5.0
        with:
          go-version: "1.26"
          cache: true

      - name: go build
        run: go build ./...

      - name: go test
        run: go test -race ./...

  goreleaser:
    name: goreleaser
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6.5.0
        with:
          go-version: "1.26"
          cache: true

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean --parallelism 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
